services:
  app:
    image: 'node:20.16.0-alpine'
    working_dir: /app
    env_file:
      - .env.docker
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
